# Display
Output img/human-vs-random-bot.gif
Set FontSize 24
Set Width 1100
Set Height 900

# Run Ultimate Tic Tac Toe
Hide
Type "lein run"
Enter
Sleep 1s
Show

# Start the game
Sleep 2s
Enter

# Play the game
# X
Sleep 750ms
Type "5"
Sleep 250ms
Enter
Sleep 500ms
Type "5"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "5"
Sleep 250ms
Enter
Sleep 500ms
Type "3"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "3"
Sleep 250ms
Enter
Sleep 500ms
Type "3"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "3"
Sleep 250ms
Enter
Sleep 500ms
Type "4"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "4"
Sleep 250ms
Enter
Sleep 500ms
Type "4"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "4"
Sleep 250ms
Enter
Sleep 500ms
Type "9"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "9"
Sleep 250ms
Enter
Sleep 500ms
Type "9"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "9"
Sleep 250ms
Enter
Sleep 500ms
Type "6"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "6"
Sleep 250ms
Enter
Sleep 500ms
Type "6"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "6"
Sleep 250ms
Enter
Sleep 500ms
Type "2"
Sleep 250ms
Enter

# X
Sleep 750ms
Type "2"
Sleep 250ms
Enter
Sleep 500ms
Type "2"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "2"
Sleep 250ms
Enter
Sleep 500ms
Type "4"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "4"
Sleep 250ms
Enter
Sleep 500ms
Type "8"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "8"
Sleep 250ms
Enter
Sleep 500ms
Type "1"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "1"
Sleep 250ms
Enter
Sleep 500ms
Type "1"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "1"
Sleep 250ms
Enter
Sleep 500ms
Type "7"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "7"
Sleep 250ms
Enter
Sleep 500ms
Type "7"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "7"
Sleep 250ms
Enter
Sleep 500ms
Type "8"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "8"
Sleep 250ms
Enter
Sleep 500ms
Type "8"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "8"
Sleep 250ms
Enter
Sleep 500ms
Type "4"
Sleep 250ms
Enter

# X
Sleep 750ms
Type "4"
Sleep 250ms
Enter
Sleep 500ms
Type "2"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "2"
Sleep 250ms
Enter
Sleep 500ms
Type "6"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "6"
Sleep 250ms
Enter
Sleep 500ms
Type "4"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "4"
Sleep 250ms
Enter
Sleep 500ms
Type "5"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "5"
Sleep 250ms
Enter
Sleep 500ms
Type "9"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "9"
Sleep 250ms
Enter
Sleep 500ms
Type "3"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "3"
Sleep 250ms
Enter
Sleep 500ms
Type "7"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "7"
Sleep 250ms
Enter
Sleep 500ms
Type "4"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "4"
Sleep 250ms
Enter
Sleep 500ms
Type "1"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "1"
Sleep 250ms
Enter
Sleep 500ms
Type "2"
Sleep 250ms
Enter

# X
Sleep 750ms
Type "2"
Sleep 250ms
Enter
Sleep 500ms
Type "1"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "1"
Sleep 250ms
Enter
Sleep 500ms
Type "6"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "6"
Sleep 250ms
Enter
Sleep 500ms
Type "5"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "5"
Sleep 250ms
Enter
Sleep 500ms
Type "7"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "7"
Sleep 250ms
Enter
Sleep 500ms
Type "3"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "3"
Sleep 250ms
Enter
Sleep 500ms
Type "2"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "2"
Sleep 250ms
Enter
Sleep 500ms
Type "3"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "3"
Sleep 250ms
Enter
Sleep 500ms
Type "5"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "5"
Sleep 250ms
Enter
Sleep 500ms
Type "1"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "1"
Sleep 250ms
Enter
Sleep 500ms
Type "8"
Sleep 250ms
Enter

# X
Sleep 750ms
Type "8"
Sleep 250ms
Enter
Sleep 500ms
Type "7"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "7"
Sleep 250ms
Enter
Sleep 500ms
Type "1"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "1"
Sleep 250ms
Enter
Sleep 500ms
Type "9"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "9"
Sleep 250ms
Enter
Sleep 500ms
Type "8"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "8"
Sleep 250ms
Enter
Sleep 500ms
Type "3"
Sleep 250ms
Enter
# O
Sleep 750ms
Type "3"
Sleep 250ms
Enter
Sleep 500ms
Type "8"
Sleep 250ms
Enter
# X
Sleep 750ms
Type "8"
Sleep 250ms
Enter
Sleep 500ms
Type "9"
Sleep 250ms
Enter

# Admire the result
Sleep 4s
